Kernel360/E2E1-Boogle

src/main/java/com/kernel360/boogle/controller/admin/book/AdminController.java
src/main/java/com/kernel360/boogle/controller/admin/book/BookController.java

feat: add AdminController

---

src/main/java/com/kernel360/boogle/controller/user/book/BookController.java
src/main/java/com/kernel360/boogle/repository/book/BookRepository.java
src/main/java/com/kernel360/boogle/service/BookService.java

책을 모두 읽어오기 위한 controller, repository, service작성 완료했습니다.
url : /api/mainPage

feat: book controller real all the books

---

src/main/java/com/kernel360/boogle/controller/user/book/BookController.java
src/main/java/com/kernel360/boogle/dto/BookDTO.java
src/main/java/com/kernel360/boogle/entity/BookEntity.java
src/main/java/com/kernel360/boogle/entity/CommonEntity.java
src/main/java/com/kernel360/boogle/service/BookService.java
src/main/resources/templates/mainPage.html

feat: book entity db persistalsis

---

src/main/java/com/kernel360/boogle/BoogleApplication.java
src/main/java/com/kernel360/boogle/controller/admin/book/AdminController.java
src/main/java/com/kernel360/boogle/dto/BookDTO.java
src/main/java/com/kernel360/boogle/entity/BookEntity.java
src/main/java/com/kernel360/boogle/entity/CommonEntity.java
src/main/java/com/kernel360/boogle/repository/book/BookRepository.java
src/main/java/com/kernel360/boogle/service/BookService.java

도서 추가 api 기능 간단하게 구현해서 올립니다.
마지막에 mr 해주시는 분 close issue 까지 부탁드려요~!

feat: save book api (draft ver.)

---

src/main/java/com/kernel360/boogle/book/controller/BookController.java
src/main/java/com/kernel360/boogle/book/service/BookService.java
src/main/java/com/kernel360/boogle/book/service/BookServiceImpl.java
src/main/resources/templates/bookSearch.html
src/main/resources/templates/mainPage.html

(html) 화면 박스말고 표같은 상하리스트로 변경
(thymeleaf) 날짜형식 변경
(bookSearch) 현준님이 바꾸신 service 구조로 리팩토링
Related to #43

chore: BookService 리팩토링 및 thymeleaf 표현양식 변경

---

src/main/resources/templates/amendBook.html

feat: add amendBook.html

---

src/main/resources/templates/amendBook.html

amendBook.html 변경된 파일이 반영되지 않아서 다시 올립니다.
#46

amendBook.html reupload

---

src/main/java/com/kernel360/boogle/book/controller/BookController.java
src/main/java/com/kernel360/boogle/book/service/BookServiceImpl.java
src/main/resources/templates/amendBook.html
src/main/resources/templates/createBook.html

도서 생성 페이지 url은 localhost:8080/admin/createBook 입니다.
Related to #56

feat: 도서 생성 페이지 구현 및 연결

---

src/main/java/com/kernel360/boogle/book/service/BookServiceImpl.java
src/main/resources/templates/mainPage.html

메인페이지 페이징 기능 구현된 거 아래에 화면 추가했고
우측 상단에 도서 생성 버튼 추가했습니다.
Related to #59

chore: 메인페이지 페이징 화면 추가 및 도서 생성 버튼 추가

---

src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
src/main/java/com/kernel360/boogle/reply/db/ReplyEntity.java
src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
src/main/java/com/kernel360/boogle/reply/model/ReplyDTO.java
src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
src/main/java/com/kernel360/boogle/reply/service/ReplyServiceImpl.java

- Reply 구조 추가
- ReplyEntity 추가 했습니다.

[feat] add Reply structure, ReplyEntity

---

src/main/resources/templates/book/admin/book-create.html
src/main/resources/templates/book/admin/book-update.html
src/main/resources/templates/book/admin/books.html
src/main/resources/templates/bookreport/admin/book-report-detail.html
src/main/resources/templates/bookreport/admin/book-reports.html
src/main/resources/templates/bookreport/book-reports.html
src/main/resources/templates/fragments/navbar.html

Related to: #105 
화면 너비를 넘어서는 페이징 버튼 수정했습니다.
어드민 화면에도 유저 화면과 같은 style 적용되도록 수정하고 navBar, footer 추가했습니다.

[feat] Pagination & Style 수정

---

src/main/java/com/kernel360/boogle/member/controller/SignupController.java
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/login.html
src/main/resources/templates/signup.html

[feat] nav, signup, login 화면 관련 수정

---

.github/workflows/build.yml

- github actions 관련 build 설정 내용 추가

[feat] Add build process

---

src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
src/main/java/com/kernel360/boogle/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/kernel360/boogle/member/controller/LoginController.java
src/main/resources/logback-spring.xml
src/main/resources/templates/login.html

- jwt 파라미터명 변경 (username -> email) 관련 일부 파일 변경
- LoginController 내 불필요 주석 제거
- logback-spring.xml -> local log level 변경 (debug to info)

[refactor] 코드 내용 공유 중 수정사항 반영

---

.gitignore
src/main/java/com/kernel360/boogle/book/controller/BookAdminController.java
src/main/java/com/kernel360/boogle/book/service/BookService.java
src/main/java/com/kernel360/boogle/bookreport/db/BookReportRepository.java
src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
src/main/java/com/kernel360/boogle/member/db/MemberRepository.java
src/main/java/com/kernel360/boogle/member/model/MemberSignupDTO.java
src/main/java/com/kernel360/boogle/member/service/MemberService.java
src/main/java/com/kernel360/boogle/mypage/controller/MyPageController.java
src/main/java/com/kernel360/boogle/mypage/model/MemberRequestDTO.java
src/main/java/com/kernel360/boogle/mypage/model/RequestMemberDTO.java
src/main/java/com/kernel360/boogle/mypage/service/MyPageService.java
src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
src/main/resources/static/css/styles.css
src/main/resources/templates/book/books.html
src/main/resources/templates/bookreport/book-reports.html
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/mypage/bookReport.html
src/main/resources/templates/mypage/communityReply.html
src/main/resources/templates/mypage/main.html
src/main/resources/templates/mypage/memberInfo.html
src/main/resources/templates/register.html

- 마이페이지 메인페이지 구현
- 회원정보 수정페이지 구현

[feat] 마이페이지구현, 회원정보수정페이지구현

---

build.gradle
src/main/java/com/kernel360/boogle/book/controller/BookController.java
src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
src/main/java/com/kernel360/boogle/bookreport/db/BookReportEntity.java
src/main/java/com/kernel360/boogle/bookreport/db/BookReportRepository.java
src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
src/main/java/com/kernel360/boogle/member/db/MemberEntity.java
src/main/java/com/kernel360/boogle/member/service/MemberService.java
src/main/java/com/kernel360/boogle/mypage/controller/MyPageController.java
src/main/java/com/kernel360/boogle/mypage/service/MyPageService.java
src/main/java/com/kernel360/boogle/reply/db/ReplyEntity.java
src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
src/main/java/com/kernel360/boogle/statistics/memberinflow/business/MemberInflowAggregation.java
src/main/resources/application-local.yml
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/mypage/communityReply.html
src/main/resources/templates/mypage/main.html
src/main/resources/templates/mypage/memberInfo.html

- 리펙토링 적용
optional<List<T>> 에서 옵셔널 제거 ( 참고: https://dev-coco.tistory.com/178)
- 마이페이지 로직개선( 민협님 조언 반영)
- 메인페이지 sticky 적용
- 원상님 코드 중복되는 부분 개선
등등

[refactor] mypage 속도개선, p6spy적용

---

.github/workflows/deploy.yml
scripts/deploy.sh
src/main/resources/application-prod.yml

- application-prod.yml 추가 (기존 EC2에 별도로 생성하여 적용하는 방식 사용X) (deploy.sh도 같이 변경)
- deploy log 남기는 경로 변경 (deploy.sh)
- deploy.yml에 'Set yml file' 단계 추가

[feat] CI/CD 변경사항 반영

---

src/main/resources/db/migration/V3.0.10__add_column_in_tables.sql
src/main/resources/db/migration/V3.0.11__drop_column_in_member.sql
src/main/resources/db/migration/V3.0.9__add_fk_in_reply.sql
src/test/resources/db/test-migration/V1.0.4__drop_column_in_member.sql

- MEMBER 테이블 컬럼 삭제 (성별, 생년월일)
- 로컬 DB, RDS DB
- REPLY 테이블 FK 추가 (MEMBER - ID)
- 기존 테이블 컬럼 not null 누락건 추가

[feat] DB 테이블 수정사항 관련 flyway SQL 반영

---

src/main/java/com/kernel360/boogle/book/db/BookEntity.java
src/main/java/com/kernel360/boogle/book/db/BookRepository.java
src/main/java/com/kernel360/boogle/book/service/BookConverter.java
src/main/java/com/kernel360/boogle/book/service/BookService.java
src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
src/main/java/com/kernel360/boogle/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/kernel360/boogle/global/jwt/JwtAuthorizationFilter.java
src/main/java/com/kernel360/boogle/global/jwt/JwtProperties.java
src/main/java/com/kernel360/boogle/global/jwt/JwtUtils.java
src/main/java/com/kernel360/boogle/member/model/MemberSignupDTO.java

- 리프레시 토큰 적용
- MemberEntity에 관한 몇가지 오류 수정

feat: refresh token

---

src/main/java/com/kernel360/boogle/book/controller/BookAdminController.java
src/main/java/com/kernel360/boogle/book/controller/BookController.java
src/main/java/com/kernel360/boogle/book/service/BookConverter.java
src/main/java/com/kernel360/boogle/book/service/BookService.java
src/main/resources/application.yml
src/test/java/com/kernel360/boogle/book/db/BookRepositoryTest.java
src/test/java/com/kernel360/boogle/book/service/BookServiceTest.java
src/test/resources/application.yml

- 테스트 코드 작성 (모두 통과)
- 테스트 DB 설정 변경
- hibernate에서 자동 테이블이 소문자로 생성된 후 인식이 되지 않는 문제 해결
- 서비스 메서드에 필요없는 인자 제거

Book 리포지토리 & 서비스 테스트 코드

---

src/main/java/com/kernel360/boogle/mypage/controller/MyPageController.java
src/main/resources/templates/mypage/memberInfo.html

[bug] 회원정보수정시 나는 whitepage 에러 수정

[bug] 회원정보수정시 나는 whitepage 에러 수정

---

build.gradle
src/main/java/com/kernel360/boogle/BoogleApplication.java
src/main/java/com/kernel360/boogle/book/db/BookRepository.java
src/main/java/com/kernel360/boogle/bookreport/controller/BookReportAdminController.java
src/main/java/com/kernel360/boogle/global/batch/MailForNewRelease.java
src/main/java/com/kernel360/boogle/global/batch/SpringBatchScheduler.java
src/main/java/com/kernel360/boogle/global/config/SpringBatchConfig.java
src/main/java/com/kernel360/boogle/global/config/SpringSchedulerConfig.java
src/main/java/com/kernel360/boogle/statistics/memberreply/scheduler/MemberReplyScheduler.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/test/resources/application.yml

배치와 스케줄러를 사용하여 월간 신간도서를 회원에게 제공하는 기능추가
- 시연 전까지는 2시간에 한번씩 불러오도록 함
- 해당 기능은 학습과 시연을 이한 것이므로, 이후 메일 삭제 또는 배치 Job수정 등으로 마무리할 예정

[feat] Spring Batch 적용; 월간 신간 도서 메일링

---

src/main/java/com/kernel360/boogle/BoogleApplication.java
src/main/java/com/kernel360/boogle/global/annotation/BoogleAnnotation.java

@EnableScheduling
@EnableAspectJAutoProxy
@EnableBatchProcessing
을 custom annoation으로 리팩토링했습니다.

[refactor] custom annotaion 추가

---

src/main/java/com/kernel360/boogle/global/batch/MailForNewRelease.java
src/main/java/com/kernel360/boogle/global/config/SpringBatchConfig.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

월간 신간 리스트를 제공하는 메일링 서비스를 중지하였습니다.
기존의 송신 메일도 삭제될 예정입니다.
삭제될 메일 : boogle.kernel360@gmail.com

[feat] 메일링 서비스 중지
